### ISSUE TITLE
LaTeX formatting of label breaks plt.plot command

### ISSUE THREAD

**Issue by twhoekstra** [twhoekstra/alpaca_kernel#1]
## Minimal example
```python
import matplotlib.pyplot as plt

plt.plot([1, 2, 3], [1, 2, 3], label='$f_{test}')
```

## Current behavior
Prints the raw data. Cannot create plot. Especially annoying for large datasets.
```python
{'label': '$f_{test}', 'fmt': '', 'data': None, 'scaley': True, 'scalex': True}[[0000803f0000004000004040], [0000803f0000004000004040]](3,)
````

## Expected behavior
A plot.

**Comment by twhoekstra** [comment]
```bash
DEBUG:root:Traceback (most recent call last):
  File "C:\Users\twh\miniconda3\envs\nb2211-arduino\lib\site-packages\alpaca_kernel-0.4.1-py3.8.egg\alpaca_kernel\kernel.py", line 796, in sresPLOT
    settings = ast.literal_eval(settings)
  File "C:\Users\twh\miniconda3\envs\nb2211-arduino\lib\ast.py", line 59, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Users\twh\miniconda3\envs\nb2211-arduino\lib\ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    {'label': '$f_{test}
                       ^
SyntaxError: EOL while scanning string literal
```
